export const types = {
    FETCH_PENDING: 'FETCH_PENDING',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
    LOAD_LIST: 'LOAD_LIST',
    LOAD_NEWS: 'LOAD_NEWS',
    LOAD_DATA: 'LOAD_DATA'
}
